Repository iangg29/natgas, pull requests merged in 2022-04, with the labels that each got.

#72 Rangos vacacionales
  client/.gitignore
  client/cypress/integration/profile/view_spec.ts
  client/cypress/support/commands.js
  client/src/assets/css/styles.css
  client/src/components/Table/EditableRow.tsx
  client/src/components/Table/ReadOnlyRow.tsx
  client/src/containers/Layout.tsx
  client/src/pages/404.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/perfil/Profile.tsx
  client/src/pages/vacaciones/ranges/CreateRange.tsx
  client/src/pages/vacaciones/ranges/Rangos.tsx
  client/src/routes/index.ts
  client/src/shared/interfaces/app.interface.ts
  client/src/shared/types/app.type.ts
  client/tsconfig.build.json
  server/app.js
  server/controllers/rangovacaciones.controller.js
  server/models/rangovacaciones.model.js
  server/routes/rangovacaciones.routes.js
Labels: Enhancement, FrontEnd

#77 Implemented new updates
  client/src/App.tsx
  client/src/assets/css/styles.css
  client/src/components/Background/Background.tsx
  client/src/components/Background/Background2.tsx
  client/src/components/Cards/BlogCard.tsx
  client/src/components/Cards/CardMiSolicitudNGB.tsx
  client/src/components/Cards/CardMiSolicitudVac.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Inputs/InputLong.tsx
  client/src/components/Inputs/InputP.tsx
  client/src/components/Inputs/Pagination.tsx
  client/src/components/Sidebar/SideBar.tsx
  client/src/components/Table/EditableRow.tsx
  client/src/components/Table/ReadOnlyRow.tsx
  client/src/components/Title/Title.tsx
  client/src/containers/Layout.tsx
  client/src/containers/Main.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Landing.tsx
  client/src/pages/TestPage.tsx
  client/src/pages/banner/FormBanner.tsx
  client/src/pages/blog/Blog.tsx
  client/src/pages/blog/FormBlog.tsx
  client/src/pages/perfil/MisSolicitudes.tsx
  client/src/pages/vacaciones/BuscarVacaciones.tsx
  client/src/pages/vacaciones/ranges/CreateRange.tsx
  client/src/pages/vacaciones/ranges/Rangos.tsx
  client/src/routes/index.ts
Labels: Enhancement, FrontEnd

#88 Se agregó la funcionalidad de modificar el perfil excepto los campos …
  client/src/pages/perfil/ActualizaPerfil.tsx
  client/src/pages/perfil/Profile.tsx
  client/src/routes/index.ts
Labels: Media, FrontEnd

#116 SignUp feature implementation
  client/package-lock.json
  client/src/pages/auth/signup.tsx
Labels: Enhancement, FrontEnd, BackEnd

#120 Frontend upgrades & major bug fixes.
  client/.env.example
  client/src/assets/css/styles.css
  client/src/components/ButtonBar/ButtonBar.tsx
  client/src/components/Cards/BlogCard.tsx
  client/src/components/Cards/CardCarousel.tsx
  client/src/components/Cards/CardMiSolicitudVac.tsx
  client/src/components/Cards/CardReporte.tsx
  client/src/components/Cards/CardRow.tsx
  client/src/components/DarkMode/Toggler.tsx
  client/src/components/Dashboard/LBlogCard.tsx
  client/src/components/Dashboard/LastBlog.tsx
  client/src/components/Footer/index.tsx
  client/src/components/Inputs/CheckBox.tsx
  client/src/components/Inputs/InputP.tsx
  client/src/components/Inputs/UploadDocument.tsx
  client/src/components/NatgasBlocks/RequestNGB.tsx
  client/src/components/News/CreateNews.tsx
  client/src/components/News/UpdateNews.tsx
  client/src/components/Profile/Stats.tsx
  client/src/components/Sidebar/SideBar.tsx
  client/src/components/Table/ReadOnlyRow.tsx
  client/src/components/Title/Title.tsx
  client/src/components/Title/TitleWhite.tsx
  client/src/components/Vacaciones/RequestVacations.tsx
  client/src/pages/Landing.tsx
  client/src/pages/asuetos/asuetos.tsx
  client/src/pages/auth/login.tsx
  client/src/pages/auth/signup.tsx
  client/src/pages/banner/FormBanner.tsx
  client/src/pages/blog/Blog.tsx
  client/src/pages/blog/EditBlog.tsx
  client/src/pages/blog/FormBlog.tsx
  client/src/pages/blog/ViewBlog.tsx
  client/src/pages/empleados/Employee.tsx
  client/src/pages/empleados/Employees.tsx
  client/src/pages/perfil/ActualizaPerfil.tsx
  client/src/pages/perfil/CompleteProfile.tsx
  client/src/pages/perfil/MisSolicitudes.tsx
  client/src/pages/perfil/Profile.tsx
  client/src/pages/reports/AllReports.tsx
  client/src/pages/reports/EditReport.tsx
  client/src/pages/reports/FormReport.tsx
  client/src/pages/vacaciones/BuscarVacaciones.tsx
  client/src/pages/vacaciones/SolicitarVac.tsx
  client/src/pages/vacaciones/VistaSolicitud.tsx
  client/src/pages/vacaciones/ranges/CreateRange.tsx
  client/src/react-app-env.d.ts
  client/src/routes/index.ts
  client/src/shared/interfaces/app.interface.ts
Labels: Enhancement, Alta, FrontEnd

#123 Debug auth
  client/src/components/ButtonBar/ButtonBar.tsx
  client/src/components/Cards/BlogCard.tsx
  client/src/containers/abacContainer.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/blog/Blog.tsx
  client/src/pages/vacaciones/VistaSolicitud.tsx
  client/src/react-app-env.d.ts
  client/src/store/actions/auth.action.ts
  client/src/store/reducers/auth.reducer.ts
  server/app.js
  server/routes/asueto.routes.js
  server/routes/banner.routes.js
  server/routes/blog.routes.js
  server/routes/natgasblock.routes.js
  server/routes/news.routes.js
  server/routes/rangovacaciones.routes.js
  server/routes/report.routes.js
  server/routes/row.routes.js
  server/routes/user.routes.js
  server/routes/vacation.routes.js
Labels: Enhancement, Alta, FrontEnd, BackEnd
