Repository iangg29/natgas, pull requests merged in 2022-03, with the labels that each got.

#24 Estructura inicial frontend.
  client/.gitignore
  client/.husky/pre-commit
  client/.prettierignore
  client/.prettierrc.json
  client/README.md
  client/cypress.json
  client/cypress/fixtures/example.json
  client/cypress/plugins/index.js
  client/cypress/support/commands.js
  client/cypress/support/index.js
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/natgas-icon.png
  client/public/robots.txt
  client/src/App.tsx
  client/src/assets/css/styles.css
  client/src/assets/img/natgas-logo-simple.png
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/tailwind.config.js
  client/tsconfig.json
Labels: FrontEnd

#26 Merge frontend.
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/react-app-env.d.ts
Labels: FrontEnd

#35 Resolved issue with postcss.
  client/package-lock.json
  client/package.json
  client/src/components/Header/Header.tsx
  client/src/index.tsx
  client/tailwind.config.js
Labels: Bug

#37 Implemented new frontend components.
  client/src/App.tsx
  client/src/assets/css/styles.css
  client/src/components/Inputs/Input.tsx
  client/src/pages/Landing.tsx
Labels: FrontEnd

#46 Solicitud de vacaciones
  client/src/components/Inputs/InputLong.tsx
  client/src/pages/SolicitarVac.tsx
  client/src/routes/index.ts
Labels: FrontEnd

#48 Vista solicitudes
  client/src/components/Cards/CardSolicitud.tsx
  client/src/components/Cards/CardSolicitudVac.tsx
  client/src/pages/VistaSolicitud.tsx
  client/src/routes/index.ts
Labels: FrontEnd

#51 Equipo2
  client/.env.example
  client/package-lock.json
  client/package.json
  client/src/components/Footer/index.tsx
  client/src/components/Header/Header.tsx
  client/src/containers/Page.tsx
  client/src/index.tsx
  client/src/pages/CompleteProfile.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Employee.tsx
  client/src/pages/Employees.tsx
  client/src/pages/Profile.tsx
  client/src/react-app-env.d.ts
  client/src/routes/index.ts
  client/src/shared/interfaces/app.interface.ts
  client/src/shared/types/app.type.ts
Labels: FrontEnd

#53 New fonts implementation
  client/src/assets/css/styles.css
  client/tailwind.config.js
Labels: Bug, FrontEnd
